# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolbox < Formula
  desc ""
  homepage "https://github.com/shivadharmi/toolbox"
  version "0.1"

  on_macos do
    url "https://github.com/shivadharmi/toolbox/releases/download/v0.1/toolbox_0.1_darwin_all.tar.gz"
    sha256 "a83c2c50eb83bf1c322fe8029b11029bbef12271a4aff9b39322195c4d5a54fe"

    def install
      bin.install "toolbox"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shivadharmi/toolbox/releases/download/v0.1/toolbox_0.1_linux_arm64.tar.gz"
      sha256 "a2a18bed1920daf58c9617e6370ed4a9aa0436492d80300806627604fadf876a"

      def install
        bin.install "toolbox"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shivadharmi/toolbox/releases/download/v0.1/toolbox_0.1_linux_amd64.tar.gz"
      sha256 "162f64a9f48d1a96d1f365bdc415bc30164c83d521f5a49c85a1de8af3add775"

      def install
        bin.install "toolbox"
      end
    end
  end
end
